### ISSUE TITLE
InSim fails with admin password containing <

### ISSUE THREAD

**Issue by xNaii** [simbroadcasts/node-insim#22]
If passing admin password contains % when InSim tries to connect, server returns:

"InSim: password does not match your multiplayer admin password"

Tried passing by `pass%word` directly to parameter and from ENV, has the same rezult

**Comment by mkapal** [comment]
Thanks for the report.

I have tested it by connecting Node InSim to an LFS server which has admin password `pass%word` and it worked OK for me, so I'm not sure how to reproduce the bug.

Can you provide more details how you managed to reproduce it? Which operating system do you use? Though It is strange that it didn't work when passed directly as an InSim parameter either.

**Comment by xNaii** [comment]
Windows 10
Node Version: 20.2.0

Used for connection
```js
let AppInSim = new InSim();
const pName = 'Dev', pHost = 'IP', pPort = 0, pAdmin = 'PRe<3ABx_Yk3W%z';

AppInSim.connect({
    IName: pName,
    Interval: 100,
    Flags: InSimFlags.ISF_MCI | InSimFlags.ISF_AXM_EDIT | InSimFlags.ISF_AXM_LOAD,
    Host: pHost ?? '127.0.0.1',
    Port: parseInt(pPort ?? '29999'),
    Admin: pAdmin,
});
```

Package.json
```json
{
  "name": "lfs-node",
  "version": "1.0.0",
  "type": "module",
  "main": "dist/index.cjs",
  "author": "xNaii",
  "license": "MIT",
  "private": true,
  "scripts": {
    "dev": "tsx watch ./src/index.ts",
    "prod": "node ./dist/index.cjs",
    "build": "tsup-node src/index.ts --dts"
  },
  "dependencies": {
    "debug": "^4.3.4",
    "dotenv": "^16.1.3",
    "prettier": "^2.8.8",
    "supports-color": "^9.3.1"
  },
  "files": [
    "**/*.js",
    "**/*.d.ts"
  ],
  "devDependencies": {
    "@types/debug": "^4.1.8",
    "@types/node": "^20.2.5",
    "node-insim": "^2.0.0",
    "tsup": "^6.7.0",
    "tsx": "^3.12.7",
    "typescript": "^5.1.3"
  }
}
```

**Comment by mkapal** [comment]
I see where the issue is - the [`unicodeToLfs`](https://github.com/simbroadcasts/unicode-to-lfs) function, which is responsible for converting Unicode strings to LFS encoding, also [escapes special characters](https://github.com/simbroadcasts/unicode-to-lfs/blob/main/src/unicodeToLfs.ts#L42), including `<` which gets converted to `^l`.

I will have to fix it by not doing the escaping logic for the `Admin` property.
