### ISSUE TITLE
Unknown IS_TINY AXI, AXC

### ISSUE THREAD

**Issue by xNaii** [simbroadcasts/node-insim#23]
After insim connects, using:
```js
AppInSim.send(
    new IS_TINY({
        ReqI: 1,
        SubT: TinyType.TINY_NCN|TinyType.TINY_NPL|TinyType.TINY_ISM|TinyType.TINY_AXI|TinyType.TINY_AXC,
    }),
);
```

Throws **Unknown IS_TINY** for AXI and AXC. Removing them removes the error

**Comment by mkapal** [comment]
`TINY_AXC` is not a request packet, but an info packet coming from LFS, so it makes sense that you can't enter it.

`TINY_AXI` seems to be working for me at least:

<img width="804" alt="image" src="https://github.com/simbroadcasts/node-insim/assets/6420535/39987c46-dc89-4b19-8a31-68f64395f59f">

**Comment by mkapal** [comment]
I could not reproduce this using Node InSim 1.0.2. This doesn't show any errors for me:

```ts
inSim.send(
  new IS_TINY({
    ReqI: 1,
    SubT: TinyType.TINY_AXI,
  }),
);
```

Can you please try again with the latest version of Node InSim? If you can still reproduce it, try sharing a minimal project where I could test it.

**Comment by xNaii** [comment]
Not getting the issue with Node InSim 3.0.0 anymore on new project. Maybe that one is bugged
