### ISSUE TITLE
CName returns random gibberish for modded vehicles

### ISSUE THREAD

**Issue by aymanhilal** [simbroadcasts/node-insim#31]
Hi,

I'm using useOnPacket which is a react-node-insim hook, the issue is CName returns random gibberish for modded vehicles only and this does not happen with default LFS vehicles. The same behavior occurs when using inSim.on() method and capturing ISP_NPL packets as well.

I'm capturing ISP_NPL packet to make an API call to retrieve the modded vehicle name in order to save it.

```
useOnPacket(PacketType.ISP_NPL, async (packet) => {
    console.log(packet.CName); // e.g: MZG Sedan shows as ]*p instead of skin id

    try {
      const req = await fetch(`https://api.lfs.net/vehiclemod/${packet.CName}`, options);
      const res = await req.json();

      setPlayers((prevPlayers) => {
        return prevPlayers.map ... etc
      });
    } catch (error) {
      // ..
    }
  });
```

Any help is greatly appreciated.

**Comment by theangryangel** [comment]
For ref - https://www.lfs.net/forum/thread/95662-New-InSim-packet-size-byte-and-mod-info explains, from the dev team.

**Comment by mkapal** [comment]
Thanks for the report, it is a bug. The `CName` property in the [IS_NPL](https://github.com/simbroadcasts/node-insim/blob/0d97c9cea0490187afc6aff9dfb4df09a44e16d3/src/packets/IS_NPL.ts#L41) packet class was wrongly annotated as a `@stringNull()` data type when being unpacked. I have changed the annotation to `@carName()` which converts the binary Skin ID to a HEX string correctly. This data type is already used in [IS_SLC](https://github.com/simbroadcasts/node-insim/blob/0d97c9cea0490187afc6aff9dfb4df09a44e16d3/src/packets/IS_SLC.ts#L28).
